"""REST API resources - infrastructure layer.

All API endpoints are route functions registered on the ``api_bp``
Blueprint (prefix ``/api``).  Dependencies are injected automatically
by the ``dependency-injector`` container.

Controllers delegate all business logic to domain command/query
handlers via the Mediator pattern — they never access repositories
directly.

The blueprint is imported and registered from the composition root.
"""

import logging

from flask import Blueprint, g, jsonify, request
from marshmallow import Schema, ValidationError, fields, validate

from dependency_injector.wiring import inject, Provide

from domain.commands.get_stats import GetStats
from domain.commands.list_alerts import ListAlerts
from domain.commands.clear_alerts import ClearAlerts
from domain.commands.list_keys import ListKeys
from domain.commands.create_api_key import CreateApiKey
from domain.commands.delete_api_key import DeleteApiKey
from infrastructure.api.auth import login_required
from mediatr import Mediator

LOG = logging.getLogger('infrastructure.api.resources')

api_bp = Blueprint('api', __name__, url_prefix='/api')


# Input schemas

class KeyCreateSchema(Schema):
    """Validates the JSON body for ``POST /api/keys``."""
    name = fields.Str(
        load_default='default',
        validate=[
            validate.Length(min=1, max=64, error='Name must be between 1 and 64 characters.'),
            validate.Regexp(
                r'^[\w\s\-]+$',
                error='Name may only contain letters, digits, spaces, underscores and hyphens.',
            ),
        ],
    )


# User info

@api_bp.route('/me')
def me():
    """Get current user information
    ---
    tags:
      - Users
    security:
      - bearerAuth: []
    responses:
      200:
        description: Authenticated user
        schema:
          type: object
          properties:
            authenticated:
              type: boolean
              example: true
            name:
              type: string
              example: "John Doe"
            email:
              type: string
              example: "john@example.com"
            picture:
              type: string
              example: "https://example.com/photo.jpg"
      401:
        description: Not authenticated
        schema:
          type: object
          properties:
            authenticated:
              type: boolean
              example: false
    """
    user = g.current_user
    if user:
        return jsonify({
            'authenticated': True,
            'name': user['name'],
            'email': user['email'],
            'picture': user['picture'],
        })
    return jsonify({'authenticated': False}), 401


# Sensor stats

@api_bp.route('/stats')
@login_required
@inject
def stats(mediator: Mediator = Provide['mediator']):
    """Get current sensor values
    ---
    tags:
      - Sensors
    security:
      - bearerAuth: []
      - apiKeyHeader: []
    responses:
      200:
        description: Current solar sensor readings
        schema:
          type: object
          properties:
            values:
              type: object
              description: Raw values for each sensor
              additionalProperties:
                type: object
                properties:
                  value:
                    type: number
                  timestamp:
                    type: string
            derived:
              type: object
              properties:
                pv_power:
                  type: number
                  description: Photovoltaic power (W)
                load_power:
                  type: number
                  description: Load power consumption (W)
                grid_power:
                  type: number
                  description: Grid power exchange (W)
                battery_power:
                  type: number
                  description: Battery power (W)
      401:
        description: Authentication required
    """
    result = mediator.send(GetStats())
    return jsonify(result.to_dict())


# CEP alerts

@api_bp.route('/cep/alerts', methods=['GET'])
@login_required
@inject
def cep_alerts_list(mediator: Mediator = Provide['mediator']):
    """List CEP alerts
    ---
    tags:
      - CEP Alerts
    security:
      - bearerAuth: []
      - apiKeyHeader: []
    responses:
      200:
        description: List of alerts generated by the CEP engine
        schema:
          type: object
          properties:
            cep_alerts:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                  rule:
                    type: string
                    example: "battery_power_high"
                  severity:
                    type: string
                    enum: [warning, critical]
                  message:
                    type: string
                    example: "Battery power (1733.0 W) exceeds 1000 W"
                  created_at:
                    type: string
                    format: date-time
      401:
        description: Authentication required
    """
    alerts = mediator.send(ListAlerts())
    return jsonify({'cep_alerts': [a.to_dict() for a in alerts]})


@api_bp.route('/cep/alerts', methods=['DELETE'])
@login_required
@inject
def cep_alerts_clear(mediator: Mediator = Provide['mediator']):
    """Clear all CEP alerts
    ---
    tags:
      - CEP Alerts
    security:
      - bearerAuth: []
      - apiKeyHeader: []
    responses:
      200:
        description: Number of alerts cleared
        schema:
          type: object
          properties:
            cleared:
              type: integer
              description: Number of alerts removed
      401:
        description: Authentication required
    """
    count = mediator.send(ClearAlerts(user_id=g.current_user['id']))
    return jsonify({'cleared': count})


# API keys

@api_bp.route('/keys', methods=['GET'])
@login_required
@inject
def keys_list(mediator: Mediator = Provide['mediator']):
    """List API keys for the current user
    ---
    tags:
      - API Keys
    security:
      - bearerAuth: []
      - apiKeyHeader: []
    responses:
      200:
        description: API keys belonging to the authenticated user
        schema:
          type: object
          properties:
            keys:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    description: Stable key identifier (SHA-256 hash)
                    example: "a1b2c3d4e5f6...abcd"
                  key:
                    type: string
                    description: Masked key (only last 4 characters visible)
                    example: "***aBcD"
                  name:
                    type: string
                    example: "default"
                  created_at:
                    type: string
                    format: date-time
      401:
        description: Authentication required
    """
    keys = mediator.send(ListKeys(user_id=g.current_user['id']))
    return jsonify({'keys': [k.to_dict() for k in keys]})


@api_bp.route('/keys', methods=['POST'])
@login_required
@inject
def keys_create(mediator: Mediator = Provide['mediator']):
    """Create a new API key
    ---
    tags:
      - API Keys
    security:
      - bearerAuth: []
      - apiKeyHeader: []
    parameters:
      - in: body
        name: body
        required: false
        schema:
          type: object
          properties:
            name:
              type: string
              description: Descriptive name for the key (1-64 characters)
              default: "default"
    responses:
      201:
        description: API key created successfully. The raw key is returned only in this response and cannot be retrieved later.
        schema:
          type: object
          properties:
            id:
              type: string
              description: Stable key identifier (SHA-256 hash)
            key:
              type: string
              description: Full raw API key (shown only once)
            name:
              type: string
            created_at:
              type: string
              format: date-time
      400:
        description: Invalid input data
      415:
        description: Content-Type is not application/json
      401:
        description: Authentication required
    """
    if not request.is_json:
        return jsonify({'error': 'Content-Type must be application/json'}), 415
    data = request.get_json() or {}
    try:
        validated = KeyCreateSchema().load(data)
    except ValidationError as exc:
        return jsonify({'error': exc.messages}), 400
    name = validated['name']
    raw_key, entry = mediator.send(
        CreateApiKey(user_id=g.current_user['id'], name=name),
    )
    resp = entry.to_dict()
    resp['key'] = raw_key          # raw key returned only at creation time
    return jsonify(resp), 201


@api_bp.route('/keys/<key_id>', methods=['DELETE'])
@login_required
@inject
def keys_delete(key_id: str, mediator: Mediator = Provide['mediator']):
    """Revoke an API key
    ---
    tags:
      - API Keys
    security:
      - bearerAuth: []
      - apiKeyHeader: []
    parameters:
      - in: path
        name: key_id
        type: string
        required: true
        description: The key identifier (SHA-256 hash) to revoke
    responses:
      200:
        description: Key revoked successfully
        schema:
          type: object
          properties:
            deleted:
              type: boolean
      404:
        description: Key not found
        schema:
          type: object
          properties:
            message:
              type: string
      401:
        description: Authentication required
    """
    deleted = mediator.send(
        DeleteApiKey(user_id=g.current_user['id'], key_id=key_id),
    )
    if deleted:
        return jsonify({'deleted': True})
    return jsonify({'message': 'Key not found'}), 404
